# models.py

from app import db

class variants(db.Model):
    
    __tablename__ = 'variants'
    
    id = db.Column(db.Integer, primary_key=True)    
    Chr = db.Column(db.String)
    Start = db.Column(db.Integer)
    End = db.Column(db.Integer)
    Ref = db.Column(db.String)
    Alt = db.Column(db.String)
    Func_refGene = db.Column(db.String)
    Gene_refGene = db.Column(db.String)
    GeneDetail_refGene = db.Column(db.Text)
    ExonicFunc_refGene = db.Column(db.Text)
    HGMD = db.Column(db.String)
    Pathogenicity = db.Column(db.String)
    HVariable = db.Column(db.String)
    Reactome = db.Column(db.Text)
    Oreganno = db.Column(db.String) 
    Regulatory = db.Column(db.String)
    OMIM = db.Column(db.String)
    OMIMnum = db.Column(db.String)
    OMIMdisorder = db.Column(db.String)
    AAChange_refGene = db.Column(db.String)
    Func_ensGene = db.Column(db.String)
    Gene_ensGene = db.Column(db.String)
    GeneDetail_ensGene = db.Column(db.Text)
    ExonicFunc_ensGene = db.Column(db.String)
    AAChange_ensGene = db.Column(db.String)
    Func_knownGene = db.Column(db.String)
    Gene_knownGene = db.Column(db.String)
    GeneDetail_knownGene = db.Column(db.Text)
    ExonicFunc_knownGene = db.Column(db.String)
    AAChange_knownGene = db.Column(db.String)
    avsnp144 = db.Column(db.String)
    clinvar_20150629 = db.Column(db.String)
    CHROM = db.Column(db.String)
    POS = db.Column(db.Integer)
    ID = db.Column(db.String)
    REF2 = db.Column(db.String)
    ALT2 = db.Column(db.String)
    QUAL = db.Column(db.String)
    FILTER = db.Column(db.String)
    AC = db.Column(db.Integer)
    AF = db.Column(db.Float)
    AN = db.Column(db.Integer)
    INFO = db.Column(db.Text)
    FORMAT = db.Column(db.Text)

    def __init__(self, **kwargs):
        vars(self).update(kwargs)
